name:
  lastname: li
  firstname:
    english: alex
    chinese: longyi

myenglishname: ${name.firstname.english}${name.lastname}


server:
  port: 8102


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    hikari:
      username: root
      password: root
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
      connection-timeout: 60000
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
    initialization-mode: always
  redis:
    host: 192.168.31.111
    port: 6399
    database: 2
    password: Chkj@2015
    timeout: 60000
    jedis:
      pool:
        max-idle: 100
        min-idle: 20
        max-active: 50
        max-wait: 150000
  cache:
    redis:
      time-to-live: 3600000
#      key-prefix: "s:"
    transaction:
      default-timeout: 30
      rollback-on-commit-failure: true

